name: surf_flutter_starter
description: CLI-tool for creating new Flutter projects, based on surf-flutter-app-template
version: 0.0.1
homepage: ''

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  args: ^2.3.0
  cli_util: ^0.3.5
  dio: ^4.0.4
  io: ^1.0.3
  process_run: ^0.12.3+2
  surf_lint_rules: ^1.4.1

dev_dependencies:
  test: ^1.20.1
