name: surf_flutter_starter
description: CLI-tool for creating new Flutter projects, based on surf-flutter-app-template
version: 0.0.4
homepage: 'https://github.com/surfstudio'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  args: 2.3.1
  archive: 3.3.5
  cli_util: 0.3.5
  dio: 4.0.6
  io: 1.0.3
  meta: 1.8.0
  test: 1.22.0
  mocktail: 0.3.0

dev_dependencies:
  surf_lint_rules: 1.5.0
