name: "Main"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  analysis:
    uses: surfstudio/flutter-ci-workflows/.github/workflows/analysis.yml@main

  testing:
    needs: analysis
    uses: surfstudio/flutter-ci-workflows/.github/workflows/testing.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
