name: test
run-name: Run tests
on: 
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: cd lib && flutter test && cd ..
